export const packLists = {
  hiking: [
    {
      ageGroup: 'Toddlers (1-3)',
      items: [
        'Small backpack or hiking diaper bag',
        'Water bottle with sippy lid (12-16 oz)',
        'Snacks: fruit pouches, crackers, cheese sticks',
        'Change of clothes (2 sets)',
        'Hat with chin strap',
        'Sunscreen (SPF 50+)',
        'Insect repellent (baby-safe)',
        'Wet wipes & diapers/pull-ups',
        'Portable changing pad',
        'Lightweight rain jacket',
        'Stroller or hiking carrier (Osprey, Deuter)',
        'Favorite stuffed animal or comfort item',
        'Small toys for rest stops',
        'First aid kit (mini)',
      ]
    },
    {
      ageGroup: 'Preschoolers (3-5)',
      items: [
        'Kid-sized backpack (5-10L)',
        'Water bottle (16-20 oz)',
        'Trail snacks: granola bars, dried fruit, string cheese',
        'Binoculars for kids',
        'Magnifying glass',
        'Small nature journal & crayons',
        'Hat with UPF protection',
        'Sunscreen (SPF 50+)',
        'Insect repellent',
        'Lightweight rain jacket',
        'Good hiking shoes or boots',
        'Change of clothes',
        'Wet wipes',
        'First aid kit',
        'Snacks for "surprise trail treasure"',
      ]
    },
    {
      ageGroup: 'Early Elementary (6-9)',
      items: [
        'Kid\'s backpack (10-15L)',
        'Water bottle with filter option (24 oz)',
        'Lunch & trail snacks',
        'Map & compass (plastic)',
        'Headlamp & spare batteries',
        'Sunscreen',
        'Insect repellent',
        'Rain jacket',
        'Hiking boots or trail shoes',
        'First aid kit',
        'Whistle (emergency)',
        'Small flashlight',
        'Nature journal & pencil',
        'Camera or phone for photos',
        'Layering fleece or jacket',
      ]
    },
    {
      ageGroup: 'Upper Elementary (10-12)',
      items: [
        'Backpack (20-30L)',
        'Water bottle (32 oz) & water purification',
        'Lunch & high-energy snacks',
        'Trail mix & electrolytes',
        'Map, compass & whistle',
        'Headlamp & spare batteries',
        'Sunscreen & lip balm',
        'Insect repellent',
        'Rain jacket & layers',
        'Hiking boots & wool socks',
        'First aid kit (comprehensive)',
        'Knife or multi-tool (supervised)',
        'Nature journal',
        'Phone & portable charger',
        'Emergency blanket',
      ]
    },
    {
      ageGroup: 'Teens (13+)',
      items: [
        'Backpack (30-50L)',
        'Water bottles (2x 32 oz) or hydration bladder',
        'Water purification method',
        'Lunch, dinner prep & snacks',
        'Map & compass & GPS app downloaded',
        'Headlamp & spare batteries',
        'Sunscreen, lip balm & sunglasses',
        'Insect repellent',
        'Rain gear & layers',
        'Hiking boots & moisture-wicking socks',
        'First aid kit & blister kit',
        'Knife/multi-tool',
        'Emergency whistle & signal mirror',
        'Phone & portable battery pack',
        'Camera (optional)',
        'Small day pack for summit runs',
      ]
    },
  ],
  camping: [
    {
      ageGroup: 'Toddlers (1-3)',
      items: [
        'Pack & play or travel crib',
        'Sleeping bag (30°F rated)',
        'Sleeping pad (foam + inflatable)',
        'Carabiner for attach toddler items',
        'Favorite sleep item (stuffed animal, blanket)',
        'Night light or glow sticks',
        'Diapers, pull-ups & wipes',
        'Sunscreen & hat',
        'Bug spray & bite relief',
        'First aid kit',
        'Change of clothes for sleeping',
        'Warm layers for night',
        'Snacks & water bottle',
        'Books or quiet toys for tent time',
        'Plastic bags for dirty laundry',
      ]
    },
    {
      ageGroup: 'Preschoolers (3-5)',
      items: [
        'Sleeping bag (30°F rated)',
        'Camping mattress (foam + kids size)',
        'Tent & footprint',
        'Headlamp with adjustable brightness',
        'Sleep aid (stuffed animal, lovie)',
        'Night light',
        'Warm pajamas & wool socks',
        'Change of clothes (2 sets)',
        'Rain boots & extra socks',
        'Sunscreen & hat',
        'Bug spray & bite relief',
        'First aid kit',
        'Flashlight for tent',
        'Camping coloring book & crayons',
        'Marshmallow roasting sticks (plastic)',
      ]
    },
    {
      ageGroup: 'Early Elementary (6-9)',
      items: [
        'Sleeping bag (20-30°F rated)',
        'Youth sleeping pad',
        'Headlamp & spare batteries',
        'Chair or sleeping pad for sitting',
        'Warm layers for night',
        'Change of clothes for each day',
        'Rain gear',
        'Water shoes or sandals',
        'Sunscreen & hat',
        'First aid kit',
        'Flashlight or headlamp',
        'Journal & pen',
        'Playing cards or travel games',
        'Water bottle',
        'Binoculars',
      ]
    },
    {
      ageGroup: 'Upper Elementary (10-12)',
      items: [
        'Sleeping bag (20°F rated)',
        'Sleeping pad (R-value 3+)',
        'Headlamp & spare batteries',
        'Personal lantern',
        'Tent stake hammer',
        'Ear plugs for sleeping',
        'Sleeping bag liner (optional)',
        'Clothes for each day + extras',
        'Rain jacket & layers',
        'Water shoes',
        'Sunscreen & hat',
        'First aid kit & toiletries',
        'Watch or compass',
        'Journal & pen',
        'Headlamp for night activities',
        'Pocket knife (with supervision)',
      ]
    },
    {
      ageGroup: 'Teens (13+)',
      items: [
        'Sleeping bag (20°F rated or lower)',
        'Sleeping pad (R-value 4+)',
        'Tent & footprint',
        'Headlamp & spare batteries',
        'Camp chair',
        'Sleeping bag liner',
        'Clothes for trip + extras',
        'Rain gear & layers',
        'Hiking boots & camp shoes',
        'Sunscreen, hat & sunglasses',
        'First aid kit & personal meds',
        'Toiletries & quick-dry towel',
        'Headlamp for night hiking',
        'Multi-tool or knife',
        'Water filtration',
        'Camera (optional)',
        'Phone & portable battery',
        'Deck of cards or travel game',
      ]
    },
  ],
  dayHikeEssentials: [
    'Water (minimum 16 oz per person, more in heat)',
    'High-energy snacks & lunch',
    'First aid kit',
    'Map & trail guide or downloaded offline map',
    'Compass',
    'Sunscreen & lip balm',
    'Hat & sunglasses',
    'Rain jacket or shell',
    'Extra layers (temperatures can change)',
    'Headlamp or flashlight',
    'Emergency whistle',
    'Pocket knife or multi-tool',
    'Blister kit & medical tape',
    'Insect repellent',
    'Hand sanitizer',
    'Toilet paper & trowel',
    'Trash bag (pack in, pack out)',
    'Baby wipes for quick cleanups',
    'Phone & portable charger',
    'Car keys in waterproof bag',
  ],
}

export const ageGroups = ['Toddlers (1-3)', 'Preschoolers (3-5)', 'Early Elementary (6-9)', 'Upper Elementary (10-12)', 'Teens (13+)']
