export const crafts = [
  {
    id: 'dandelion-crown',
    title: 'Dandelion Crown',
    materials: ['Fresh dandelions (with stems)', 'Grass', 'Small flowers'],
    duration: '20 min',
    ageRange: '3-8',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1490745825946-4b93a9d7f2e6?w=800',
    instructions:
      'Braid three long stems together to form a base, then weave dandelion heads and small flowers through the braid. Add grass blades for leaves. Tuck stems underneath to secure.',
  },
  {
    id: 'leaf Whistle',
    title: 'Leaf Whistle',
    materials: ['Fresh green leaf (elm, maple, or aspen)', 'Two hands'],
    duration: '10 min',
    ageRange: '5-12',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1518882605630-8eb700e01287?w=800',
    instructions:
      'Fold a fresh green leaf accordion-style, place to lips, blow hard. The crack of the leaf makes a satisfying whistle. Works best with thin, flexible leaves.',
  },
  {
    id: 'grass-blade-flute',
    title: 'Grass Blade Flute',
    materials: ['Wide grass blade', 'Two hands'],
    duration: '5 min',
    ageRange: '6-12',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1518882605630-8eb700e01287?w=800',
    instructions:
      'Hold a wide grass blade between thumbs, blow across the gap between thumbs. Adjust tension and gap size to change pitch. Makes a reedy, honking sound.',
  },
  {
    id: 'flowerLei',
    title: 'Flower Lei',
    materials: ['Small flowers (clover, daisies, tiny blooms)', 'Grass stems or thread', 'Patience'],
    duration: '30 min',
    ageRange: '5-10',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
    instructions:
      'Pierce flower stems with needle (or use thin grass stems as thread), string flowers one by one into a loop. Wear immediately or press to preserve.',
  },
  {
    id: 'mudPaint',
    title: 'Mud Paint',
    materials: ['Dirt', 'Water', 'Sticks', 'Large leaves or rocks to paint on'],
    duration: '30 min',
    ageRange: '2-8',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800',
    instructions:
      'Mix dirt with water until you get different consistencies - thin for washes, thick for bold strokes. Paint on large leaves or smooth rocks. Watch how the earth makes beautiful browns and grays.',
  },
  {
    id: 'acornCap Necklace',
    title: 'Acorn Cap Necklace',
    materials: ['Acorn caps', 'Thin drill bit or needle', 'Twine or cord', 'Beads (optional)'],
    duration: '25 min',
    ageRange: '6-12',
    indoor: true,
    imageUrl: 'https://images.unsplash.com/photo-1518882605630-8eb700e01287?w=800',
    instructions:
      'Poke a small hole through each acorn cap. Thread twine through, adding beads as you go. Knot at ends to secure. The caps make satisfying rattling sounds.',
  },
  {
    id: 'stickBundles',
    title: 'Magic Stick Bundles',
    materials: ['Collected sticks of various lengths', 'Twine or ribbon', 'Dried flowers (optional)'],
    duration: '20 min',
    ageRange: '4-10',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e35a6?w=800',
    instructions:
      'Gather sticks in a bundle, tie tightly with twine in the middle. Fan out the tops slightly. Add dried flowers or wrap ribbon around the tie for a decorative display piece.',
  },
  {
    id: 'flowerCollage',
    title: 'Petal Mosaic',
    materials: ['Fresh flower petals', 'Cardboard', 'White glue', 'Small paintbrush'],
    duration: '45 min',
    ageRange: '4-10',
    indoor: true,
    imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
    instructions:
      'Sort petals by color, arrange on cardboard in patterns or pictures. Glue each petal down carefully. Creates beautiful abstract art when petals press flat as they dry.',
  },
  {
    id: 'rockTower',
    title: 'Rock Balancing Art',
    materials: ['Smooth river rocks', 'Patience', 'A flat surface'],
    duration: '30 min',
    ageRange: '3-12',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1518882605630-8eb700e01287?w=800',
    instructions:
      'Find flat-bottomed rocks of varying sizes. Stack them one on top of another, searching for the balance point of each. Go as high as you dare. Takes focus and steady hands.',
  },
  {
    id: 'barkRubbing',
    title: 'Bark Rubbing',
    materials: ['Thin paper', 'Soft crayons or colored pencils', 'Tree bark to explore'],
    duration: '30 min',
    ageRange: '4-10',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1518882605630-8eb700e01287?w=800',
    instructions:
      'Place paper against tree bark, rub crayon sideways across the surface. The texture of each tree - smooth birch, rough oak - reveals itself in lines and patterns.',
  },
  {
    id: 'seedPodBirds',
    title: 'Seed Pod Birds',
    materials: ['Dry seed pods (milkweed, cottonwood)', 'Small twigs', 'Googly eyes', 'Glue'],
    duration: '40 min',
    ageRange: '5-10',
    indoor: true,
    imageUrl: 'https://images.unsplash.com/photo-1518882605630-8eb700e01287?w=800',
    instructions:
      'Shape cottonwood pods into bodies, stick twigs into sides for wings. Glue on googly eyes. Each seed pod becomes a unique little bird with personality.',
  },
  {
    id: 'leafBow',
    title: 'Maple Leaf Bow',
    materials: ['Large maple leaves (fresh)', 'Small twig or stem', 'Twine'],
    duration: '15 min',
    ageRange: '4-10',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1518882605630-8eb700e01287?w=800',
    instructions:
      'Fold a large maple leaf in half lengthwise, wrap a small twig or stem around the crease, pull tight. The leaf puckers into a tiny bow shape perfect for decorating or gifting.',
  },
  {
    id: 'stoneFairyHouse',
    title: 'Stone Fairy House',
    materials: ['Flat stones', 'Moss', 'Small sticks', 'Acorn caps', 'Tiny shells', 'Glue gun'],
    duration: '1 hour',
    ageRange: '5-10',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=800',
    instructions:
      'Stack flat stones to form walls of a tiny house. Use moss as roofing. Decorate with acorn cap doorways, shell windows, stick chimneys. Place in a garden corner.',
  },
  {
    id: 'flowerFace',
    title: 'Petal Faces',
    materials: ['Leaves', 'Flower petals', 'Seeds', 'Glue', 'Paper plate or cardboard'],
    duration: '30 min',
    ageRange: '3-8',
    indoor: true,
    imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
    instructions:
      'Arrange petals, seeds, and leaves on paper to create faces - petal hair, seed eyes, leaf mouth. Make happy, silly, or grumpy nature faces.',
  },
  {
    id: 'nestBuilding',
    title: 'Tiny Bird Nest',
    materials: ['Small twigs', 'Dried grass', 'Moss', 'Feathers', 'Glue'],
    duration: '45 min',
    ageRange: '5-12',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=800',
    instructions:
      'Coil twigs into a small bowl shape, tucking ends in as you go. Weave grass and moss through the twigs. Add feathers inside for lining. Makes a sweet spring decoration.',
  },
  {
    id: 'charcoalDrawing',
    title: 'Charcoal Drawing',
    materials: ['Burnt sticks from campfire or fireplace', 'Paper', 'Soft brush'],
    duration: '20 min',
    ageRange: '6-12',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1518882605630-8eb700e01287?w=800',
    instructions:
      'Collect charred sticks from a fire (safe, cooled). Break open to reveal soft charcoal inside. Draw on paper for beautiful grayscale art. Blend with fingers or brush for shading.',
  },
  {
    id: 'driedFlowerPicture',
    title: 'Dried Flower Frame',
    materials: ['Pressed and dried flowers', 'Old picture frame', 'White glue', 'Background paper'],
    duration: '1 hour',
    ageRange: '6-12',
    indoor: true,
    imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
    instructions:
      'Arrange dried flowers on background paper in a design. Glue carefully. Place in frame. The colors of summer preserved to enjoy all year long.',
  },
  {
    id: 'twigLetters',
    title: 'Twig Letters',
    materials: ['Small sticks (varied sizes)', 'Twine', 'Hot glue gun'],
    duration: '45 min',
    ageRange: '5-10',
    indoor: false,
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e35a6?w=800',
    instructions:
      'Form letters (first initial works great) by arranging sticks. Glue ends together, wrap twine around joints for extra hold. Makes a charming natural room decoration.',
  }
];
